package ink.pmc.framework.bridge

const val HEARTBEAT_CHECK_INTERVAL_SECS = 5L
const val HEARTBEAT_SEND_INTERVAL_SECS = HEARTBEAT_CHECK_INTERVAL_SECS
const val HEARTBEAT_THRESHOLD_SECS = HEARTBEAT_CHECK_INTERVAL_SECS
const val HEARTBEAT_GRACE_PERIOD_SECS = 2L